#!/bin/bash

MOZ=$(realpath ../bin/moz)
LIB=$(realpath ../library)
DEMO=$(realpath ../demo)
TEST=$(realpath .)

test_file()
{
  $MOZ --libpaths=$LIB $1 > test.out
  diff test.out $2
}

test_demo_file()
{
  echo "Test" $1".moz"
  test_file $DEMO/$1".moz" "expected-output-"$1".txt"
}

test_local_file()
{
  echo "Test" $1".moz"
  test_file $TEST/$1".moz" "expected-output-"$1".txt"
}

test_dill_file()
{
  echo "Test" $1".moz"
  test_file $DEMO/dill/$1".moz" "expected-output-dill-"$1".txt"
}

test_2dmech_file()
{
  echo "Test" $1".moz"
  test_file $DEMO/2DMech/$1".moz" "expected-output-2DMech-"$1".txt"
}

test_file2()
{
  echo "Test $(basename $1)"
  TEST_PATH="$(realpath $1)"
  OUTPUT_PATH="${TEST_PATH%%.moz}.txt"
  test_file $TEST_PATH $OUTPUT_PATH
}

test_files()
{
  echo "Running tests in $1"
  for f in $1/*.moz;
  do
    test_file2 $f
  done
}

# test_demo_file "modelica-mechsys"
# test_demo_file "breaking-controlsys"
# test_demo_file "capacitor-switch"
# test_demo_file "controlsys"
# test_demo_file "hybrid-ball-stairs"
# test_demo_file "lotkavolterra"
# test_demo_file "pendulum"
# test_demo_file "synchronous-test"
# test_demo_file "timer"
# test_demo_file "very-fast-fly"

# test_local_file "overloading"
# test_local_file "multibranch"
# test_local_file "regression-CapitalLetterInFilenameBugOnLinux"

# test_dill_file "bounce2"
# test_dill_file "lcd"
# test_dill_file "lr"
# test_dill_file "step"
# test_dill_file "svr"
# test_dill_file "lrd"
# test_dill_file "lrd2"
# test_dill_file "clutch"

test_files "matrix"
test_files "svector"
test_files "sreal"
test_files "eqformulation"

rm -f test.out
